---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 158.160.54.225
    jenkins-agent-01:
      ansible_host: 51.250.70.218
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: marc
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_test