---
all:
  hosts:
    nexus-01:
      ansible_host: 158.160.58.93
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: marc
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_test