version: '3.9'
services:

  es-hot:
    image: elasticsearch:7.17.9
    container_name: es-hot
    environment:
      - node.name=es-hot
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-warm
      - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    depends_on:
      - es-warm
      - fluent-bit
    logging:
      driver: fluentd
      options:
        tag: es_hot


  es-warm:
    image: elasticsearch:7.17.9 
    container_name: es-warm
    environment:
      - node.name=es-warm
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es-hot
      - cluster.initial_master_nodes=es-hot,es-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - data02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    networks:
      - elastic
    logging:
      driver: fluentd
      options:
        tag: es_warm    
    depends_on:
      - fluent-bit      

  kibana:
    image: kibana:7.17.9
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es-hot:9200
      ELASTICSEARCH_HOSTS: '["http://es-hot:9200","http://es-warm:9200"]'
    networks:
      - elastic
    depends_on:
      - es-hot
      - es-warm
      - fluent-bit
    logging:
      driver: fluentd
      options:
        tag: kibana     

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./pinger/run.py:/opt/run.py:Z
    entrypoint: python3 /opt/run.py
    networks:
      - elastic
    logging:
      driver: fluentd
      options:
        tag: some_app
    depends_on:
      - fluent-bit

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit:1.8
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./configs/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./configs/parsers.conf:/fluent-bit/parsers/parsers.conf:ro
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  elastic:
    driver: bridge
