---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse

  - src: git@github.com:marc010/vector-role.git
    scm: git
    version: "0.0.4"
    name: "vector-role"

  - src: git@github.com:marc010/lighthouse-role.git
    scm: git
    version: "0.0.5"
    name: "lighthouse-role"