---
- name: Install Clickhouse
  hosts: clickhouse-01
  roles: 
    - clickhouse

- name: Install Vector
  hosts: vector-01
  roles: 
    - vector-role


- name: Install Lighthouse
  hosts: lighthouse-01
  roles: 
    - lighthouse-role
