{
 "title": "New Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "MemFree"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\"}",
     "legendFormat": "MemAvailable"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\"}",
     "legendFormat": "Total size"
    },
    {
     "expr": "node_filesystem_free_bytes{instance=\"nodeexporter:9100\",mountpoint=\"/\"}",
     "legendFormat": "Free size"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (insance) (rate(node_load1{}[$__rate_interval]))",
     "legendFormat": "CPULA 1"
    },
    {
     "expr": "avg by (insance) (rate(node_load5{}[$__rate_interval]))",
     "legendFormat": "CPULA 5"
    },
    {
     "expr": "avg by (insance) (rate(node_load15{}[$__rate_interval]))",
     "legendFormat": "CPULA 15"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}